version: '3.7'
  
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./RinPy
    command: python manage.py runserver 0.0.0.0:8000  
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
  migrate:
    build: ./RinPy
    command: python manage.py migrate --noinput
    depends_on:
      - db
      - web
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
