version: '3.7'
  
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./RinPy
    command: python manage.py runserver 0.0.0.0:8000  
    volumes:
      - static_volume:/code/staticfiles
      - /var/run/docker.sock:/var/run/docker.sock
      - exec_volume:/code/exce
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
  migrate:
    build: ./RinPy
    command: python manage.py migrate --noinput
    depends_on:
      - db
      - web
    env_file:
      - ./.env.dev
    volumes:
      - static_volume:/code/staticfiles
  static:
    build: ./RinPy
    command: python manage.py collectstatic --noinput
    depends_on:
      - web
      - db
    env_file:
      - ./.env.dev
    volumes:
      - static_volume:/code/staticfiles
  excecutor:
    build: ./RinPy
    volumes:
      - exec_volume:/code/exce

volumes:
  postgres_data:
  static_volume:
  exec_volume:
